version: "3"
services:
  autoheal:
     container_name: 'tor-autorestart'
     restart: 'on-failure'
     image: 'willfarrell/autoheal'
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     environment:
       - "AUTOHEAL_CONTAINER_LABEL=all"
  tor:
    container_name: 'tor'
    image: 'deathmond1987/tor_for_r:latest'
#    image: 'docker.io/library/tor-for-ru:test'
    labels:
      - autoheal=true
    environment:
      TOR_LOG_CONFIG: 'false'
      TOR_PROXY: 'true'
      TOR_PROXY_PORT: '0.0.0.0:9050'
      TOR_PROXY_ACCEPT: 'accept *'
      TOR_CONTROL: 'true'
      TOR_CONTROL_PORT: ''
      TOR_CONTROL_PASSWORD: ''
      TOR_CONTROL_COOKIE: 'true'
      TOR_SERVICE: 'false'
      TOR_RELAY: 'false'
      TZ: "Europe/Moscow"
    volumes:
      - "./tor:/tor/"
    ports:
      - "9050:9050/tcp"
#      - "9051:9051"
    restart: 'always'
  nyx:
    container_name: 'nyx'
    image: 'deathmond1987/tor_for_r:latest'
    volumes:
      - "./tor:/tor/"
    environment:
      TZ: "Europe/Moscow"
    entrypoint: |
           ash -c "sleep 10 && /usr/bin/nyx -s /tor/control.socket"
